Refactor code style, basic corrections
ardaasln/eksisong pull request #1
Opened 2018-01-15 19:58 UTC by elhanarinc

* Module.exports vs export [Check here](https://hackernoon.com/import-export-default-require-commandjs-javascript-nodejs-es6-vs-cheatsheet-different-tutorial-example-5a321738b50f)
* Another good reference for exports [Check here](https://stackoverflow.com/questions/34645731/export-more-than-one-variable-in-es6/34645759)

2018-01-15 21:11 UTC, ardaasln commented on src/app.js
> +app.use(helmet());
Use `import helmet from 'helmet';` at the top

2018-01-15 21:18 UTC, ardaasln commented on src/routes/index.js
> +export {router};
Also fix app.js
-let index = require('./routes/index');
+import {router as index} from './routes/index';

2018-01-15 21:21 UTC, ardaasln commented on src/routes/users.js
> +export {router};
Also fix app.js
-let users = require('./routes/users');
+import {router as users} from './routes/users';

2018-01-15 21:22 UTC, ardaasln commented on src/background/init.js
> +export {backgroundTask};
Also add clientSecrets to exports
+export {backgroundTask, clientSecrets};

2018-01-15 21:25 UTC, ardaasln commented on src/bin/www
> +import backgroundTask as bg from '../background/init.js'
Syntax error
`-import backgroundTask as bg from '../background/init.js'`
`+import {backgroundTask as bg} from '../background/init.js'`

2018-01-15 21:26 UTC, ardaasln commented on src/lib/crawl.js
> +import clientSecrets from '../background/init.js';
We have now multiple exports at init.js so:
`-import clientSecrets from '../background/init.js';`
`+import {clientSecrets} from '../background/init.js';`

2018-01-15 21:27 UTC, ardaasln requested changes
Commented on related code chunks for changes

2018-01-16 06:53 UTC, elhanarinc commented
Review done. @ardaasln

2018-01-16 15:36 UTC, ardaasln approved these changes

2018-01-16 15:37 UTC, merged